#!/usr/bin/env bash
# Replace git-LFS pointer files in hyperframes/source with their real content.
#
# GitHub serves LFS objects for public repos over media.githubusercontent.com,
# so no git-lfs client is required. Each object is verified against the sha256
# recorded in its pointer file.
#
# Which pointers to resolve:
#   - skills assets      (.agents/skills, .claude/skills, skills/)  always
#   - test src assets    (packages/**/src/**)                       always
#   - test outputs       (packages/**/output/**)                    only with --with-outputs
# The remaining pointers stay as pointers; hyperframes/source/LFS_STATUS.md
# records exactly what is real and what is a pointer.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/hyperframes/source"
WITH_OUTPUTS="${1-}"
BASE="https://media.githubusercontent.com/media/heygen-com/hyperframes/main"

[ -d "$SRC" ] || { echo "missing $SRC"; exit 1; }

# Every LFS pointer file in the tree.
mapfile -t POINTERS < <(grep -rl '^version https://git-lfs.github.com/spec/v1' "$SRC" 2>/dev/null | sort || true)
echo "pointer files: ${#POINTERS[@]}"

ok=0; skip=0; fail=0; fetched_bytes=0
: > "$ROOT/hyperframes/LFS_STATUS.md"
{
  echo "# LFS status of hyperframes/source"
  echo
  echo "Generated by scripts/fetch-hf-lfs.sh."
  echo
  echo "Real content fetched:"
} >> "$ROOT/hyperframes/LFS_STATUS.md"

for p in "${POINTERS[@]}"; do
  rel="${p#"$SRC"/}"
  oid="$(awk '/^oid sha256:/{sub(/^sha256:/, "", $2); print $2}' "$p")"
  size="$(awk '/^size /{print $2}' "$p")"

  case "$rel" in
    */output/*) if [ "$WITH_OUTPUTS" != "--with-outputs" ]; then
        skip=$((skip+1)); continue; fi ;;
  esac

  # Verify what is already there, if real.
  if [ -f "$p" ] && [ "$(stat -c %s "$p")" != "$(printf '%s' "${size:-0}")" ]; then
    have="$(sha256sum "$p" | awk '{print $1}')"
    if [ "$have" = "$oid" ]; then ok=$((ok+1)); continue; fi
    echo "fetch $rel ($(( size / 1048576 )) MB)"
    if curl -fL --retry 3 --retry-delay 2 -o "$p.tmp" "$BASE/$rel" 2>/dev/null; then
      got="$(sha256sum "$p.tmp" | awk '{print $1}')"
      if [ "$got" = "$oid" ]; then
        mv "$p.tmp" "$p"
        ok=$((ok+1)); fetched_bytes=$((fetched_bytes+size))
        echo "- \`$rel\` ($(( size / 1048576 )) MB)" >> "$ROOT/hyperframes/LFS_STATUS.md"
      else
        rm -f "$p.tmp"; fail=$((fail+1))
        echo "HASH MISMATCH $rel (expected $oid, got $got)" >&2
      fi
    else
      rm -f "$p.tmp"; fail=$((fail+1)); echo "download failed: $rel" >&2
    fi
  fi
done

{
  echo
  echo "Left as LFS pointers: $skip files"
  if [ "$skip" != 0 ]; then
    echo
    echo "These are generated test outputs. Fetch them with:"
    echo '```'
    echo "bash scripts/fetch-hf-lfs.sh --with-outputs"
    echo '```'
  fi
} >> "$ROOT/hyperframes/LFS_STATUS.md"

echo "fetched: $ok (${fetched_bytes} bytes)  pointers kept: $skip  failed: $fail"
[ "$fail" = 0 ] || exit 1
